services:
  db:
    image: postgres:latest
    container_name: mcpjungle-db
    environment:
      POSTGRES_USER: mcpjungle
      POSTGRES_PASSWORD: mcpjungle
      POSTGRES_DB: mcpjungle
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mcpjungle-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jlwainwright@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Jlwain@321
    ports:
      - "5050:80"
    depends_on:
      - db

  mcpjungle:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: mcpjungle-server
    environment:
      DATABASE_URL: postgres://mcpjungle:mcpjungle@db:5432/mcpjungle
      DEBUG_LEVEL: debug
      ENABLE_PPROF: true
      PPROF_PORT: 6060
    ports:
      - "8080:8080"
      - "6060:6060"  # pprof port for memory profiling
    depends_on:
      - db

  mcpjungle-web:
    build: ./web
    container_name: mcpjungle-web
    ports:
      - "3001:3001"
    depends_on:
      - mcpjungle

volumes:
  db_data:
